### ISSUE TITLE
Night Mode Switch Not Appearing

### ISSUE THREAD

**Issue by monsieurlatte** [nberardi/scrypted-dyson#3]
Finally got back around to testing this and wow, what a great job, it's working perfectly now for me, however I have the checkbox for night mode and I dont see a switch appearing anywhere?  I have tried removing the accessory after making the change and it's not showing up still.  Thoughts?

**Comment by nberardi** [comment]
I appreciate giving the plug-in a second try. Certain capabilities, haven’t been translated into HomeKit, mostly due to missing bindings in Scrypted. I’m continuing to work on those to close the gap.  

By the way I know this isn't the ideal solution, but I have implemented them on the Scrypted control page for the device, as well as many other capabilities that were never part of the original homebridge implementation.

**Comment by ghost** [comment]
Also 'Continuous Monitoring' switch is missing from HomeKit. It works well in the Scripted control page, so I'm looking forward to testing it when you get around to implementing both in HomeKit.
Thanks for the plugin!
